kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["hostmount-anyuid"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
