apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /export
    server: 192.168.133.9
  persistentVolumeReclaimPolicy: Retain
