---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true 
    prometheusK8s:
      retention: 36h
      externalLabels:
        cluster: ocp4-bm-t1-lab-local
      volumeClaimTemplate:
        metadata:
          name: prometheusdb
        spec:
          storageClassName: ocs-external-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 30Gi
    alertmanagerMain:
      volumeClaimTemplate:
        metadata:
          name: alertmanager
        spec:
          storageClassName:ocs-external-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 30Gi
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    receivers:
      - name: dev-null
      - name: slack-test
        "slack_configs":
        - api_url: "{{ slack_services_url }}"
          channel: "#openshift-alerts"
          send_resolved: true
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_interval: 5m
      group_wait: 30s
      receiver: 'null'
      repeat_interval: 12h
      routes:
        - receiver: dev-null
          match:
            alertname: Watchdog
        - receiver: slack-test
          match:
            severity: critical
