apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 1d
      infra:
        maxAge: 1d
      audit:
        maxAge: 1d
    elasticsearch:
      nodeCount: 3
      tolerations:
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Exists
        tolerationSeconds: 6000
      storage: {}
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: 200m
          memory: 8Gi
      proxy:
        resources:
          limits:
            memory: 256Mi
          requests:
             memory: 256Mi
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
      tolerations:
      - effect: NaExecute
        key: node-role.kubernetes.io/infra
        operator: Exists
        tolerationSeconds: 6000
  collection:
    logs:
      type: "fluentd"
      fluentd:
        tolerations:
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          operator: Exists
          tolerationSeconds: 6000
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
