---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 900m
          memory: 2Gi
