---
apiVersion: v1
kind: Service
metadata:
  name: external-rsyslog-1
  labels:
    extsvc: external-rsyslog-1
spec:
  ports:
    - protocol: TCP
      port: 1514
      targetPort: 1514
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "external-rsyslog-1"
  labels:
    extsvc: external-rsyslog-1
subsets:
- addresses:
  - ip: 10.1.10.10
    #nodeName: rsyslog-1.example.com
  ports:
  - name: rsyslog
    port: 1514
    protocol: TCP
