apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: localblock
  namespace: openshift-local-storage
spec:
  storageClassName: lso
  volumeMode: Filesystem
  fstype: ext4
  maxDeviceCount: 10
  deviceInclusionSpec:
    minSize: 40G
    maxSize: 60G
    deviceTypes:
    - disk
    deviceMechanicalProperties:
    - Rotational
