apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: bW9kZGk6JDJ5JDA1JFRYcEZLelJnUGdqVVAzbS9OS09KTi5GQk1SQXZERGRHQ0t6S0N2NnJCdmxia1gzUUl6WXppCmRldmVsb2RvbnRlOiQyeSQwNSQuU2R4d29nSDhlV0tUdnFkb1VYOW51YXFJbXNnZkFENC81UUpiMTUwNTJZa3V1SllkeVF3QwphcmNoOiQyeSQwNSQ1YmxlSXZwN0MzZzdISE00WEkvbFllMVo5c0Q5dG03aEptdm5XWXI0ZHVtU1pza1AvQmtBMgo=

