apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ipa-tls-ca
  namespace: openshift-config
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDhTCCAm2gAwIBAgIBATANBgkqhkiG9w0BAQsFADA0MRIwEAYDVQQKDAlMQUIu
    TE9DQUwxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yMDEwMjcx
    MjM4MDVaFw00MDEwMjcxMjM4MDVaMDQxEjAQBgNVBAoMCUxBQi5MT0NBTDEeMBwG
    A1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA3qM/FyD8TrWQI5Xjp1C+F3s1r/mbOAQarWwVG3MuC63yITKY
    NmTKjzVUGGcY11TReX75//HfP+iiD3l+wlMkSzZoi6bYkvplj0UbDtLpPq/JlzV5
    Ekf1luOBg36Yi0JzMhVmMl+zf9UgrFP8fkgABGrthOasJceP++j5BBj8oj2Za7v8
    7TOqf/q98OfRnxUmAJrIMIBkFWfox/BwytphOuPdsiRv7NOwFKbCLhAX96p8dSJ3
    FjL4/j8Gd2I2p/74UWg3NfSPqAvtfEtUY/B7Ar+kQOXRv20nKHH15tusWmVYNmqb
    4NH+8IS7a4Pkzg8EhW/svI+TnCqhgcs6wFUu+wIDAQABo4GhMIGeMB8GA1UdIwQY
    MBaAFHAtI/GxuPDFfkp0cQ+hJmBjkk8eMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0P
    AQH/BAQDAgHGMB0GA1UdDgQWBBRwLSPxsbjwxX5KdHEPoSZgY5JPHjA7BggrBgEF
    BQcBAQQvMC0wKwYIKwYBBQUHMAGGH2h0dHA6Ly9pcGEtY2EubGFiLmxvY2FsL2Nh
    L29jc3AwDQYJKoZIhvcNAQELBQADggEBALajqq1kSr/IlxCelKu6d2Kql5K8H9wJ
    REsx5lFZS5Sd0n2CGQMFoHixqjPKnVHpB2WmgNILhUklLogCYSyWS69AxHskDSY/
    lou0OdL7PnogKqH1ywLPopSeZY8d9DmzOyf+gqphWpLniHvblXxkQbrmQW4Y+JY6
    4m/x5QNR1dd2fey7PE4GTnkxYv6T8czyJ7BqLDkV8cZjJQ12vdTRL/yZt+o+asbx
    JIU/+p9L9vKOkP1C1xe5VyWFfzcOUu1ACyzl3oVb1OPJ2XCdF6/G2JskUVl67Mvo
    J3J8PUWVQM/Eo63JTWyiqbT838WU4t7edetddIulTWNZRcdRVQdy6+g=
    -----END CERTIFICATE-----
    
