kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-provisioner-binding
  namespace: nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner-sa
roleRef:
  kind: Role
  name: nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
