apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: petclinic
spec:
  storageClassName: nfs-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
