apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-static
  namespace: petclinic
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: nfs
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
